INSERT INTO public.members ("position", name, bio, member_img, role_id, email, password) VALUES
('заменик председника', 'Андреј Донев',
 'Рођен је 4. децембра 2003. године у Београду. Тренутно је студент четврте године на смеру електроника и дигитални системи.',
 NULL, 1, 'da220633d@student.etf.bg.ac.rs', NULL),
('члан', 'Анђела Нинковић', NULL, NULL, 3, 'na253099m@student.etf.bg.ac.rs', NULL),
('члан', 'Босиљка Радовановић', NULL, NULL, 3, 'rb200454d@student.etf.bg.ac.rs', NULL),
('члан', 'Вељко Гајић', NULL, NULL, 3, 'gv253375m@student.etf.bg.ac.rs', NULL),
('члан', 'Вукашин Јевремовић', NULL, NULL, 3, 'jv253128m@student.etf.bg.ac.rs', NULL),
('члан', 'Душан Калуђеровић', NULL, NULL, 3, 'kd180538d@student.etf.bg.ac.rs', NULL),
('члан', 'Ена Грубор', NULL, NULL, 3, 'ge253291m@student.etf.bg.ac.rs', NULL),
('члан', 'Лазар Бељић', NULL, NULL, 3, 'vl170516d@student.etf.bg.ac.rs', NULL),
('члан', 'Лазар Вујчић', NULL, NULL, 3, 'bl243003m@student.etf.bg.ac.rs', NULL),
('члан', 'Лука Томовић', NULL, NULL, 3, 'tl230169d@student.etf.bg.ac.rs', NULL),
('члан', 'Лука Царевић', NULL, NULL, 3, 'cl220023d@student.etf.bg.ac.rs', NULL),
('члан', 'Милан Тошић', NULL, NULL, 3, 'tm220195d@student.etf.bg.ac.rs', NULL),
('члан', 'Милица Стефановић', NULL, NULL, 3, 'sm200646d@student.etf.bg.ac.rs', NULL),
('председник', 'Никола Лапчевић',
 'Рођен је 8. августа 2002. године у Нишу. Тренутно је студент четврте године на смеру енергетика.',
 NULL, 1, 'aleksandarbubalo99@gmail.com', NULL),
('члан', 'Рајко Лапчевић', NULL, NULL, 3, 'lr230484d@student.etf.bg.ac.rs', NULL),
('члан', 'Сара Гојковић', NULL, NULL, 3, 'gs210653d@student.etf.bg.ac.rs', NULL),
('члан', 'Соња Војновић', NULL, NULL, 3, 'vs210231d@student.etf.bg.ac.rs', NULL),
('члан', 'Томислав Беновић', NULL, NULL, 3, 'bt220090d@student.etf.bg.ac.rs', NULL);